# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/bdegreve/bramz-pre-commit-hooks.git
    rev: 11b9312f25f34693211b214cc4c910cb1cc7c475
    hooks:
      - id: bramz-fix-copyright
        args: [--author=Bram de Greve, --prefix=Copyright]
        exclude: ^setup.py$
